<a href="https://colab.research.google.com/github/pgordin/GraphsSN2024_1/blob/main/Graphs2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Package import.

In [1]:
import numpy as np
from random import random, seed

## Graph functions

In [2]:
def print_matrix(vertices, matrix):
  """
  Printing a graph given by adjacency matrix
  """
  n = len(matrix)
  if (vertices is not None) and (len(vertices) == n):
    vv = vertices
  else:
    vv = range(1, n+1)
  for i in range(n):
    print(vv[i], ":", end="")
    for j in range(n):
      if matrix[i, j]:
        print(" ", vv[j], end="")
    print("")

def print_graph(graph):
  """
  Printing of a graph (given as a dictionary/neighbouring list)
  """
  for v in graph:
    print(v, ":", end="")
    for u in graph[v]:
      print(" ", u, end="")
    print("")

## Making and modyfing graphs

In [3]:
def add_vertex(graph, vertex):
  """
  Add a new vertex to an existing graph
  """
  if vertex not in graph:
    graph[vertex] = []

def add_arc(graph, arc):
  """
  Given pair of vertices (arc variable) add an arc to an existing graph
  We consider simple, directed graphs.
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)

def add_edge(graph, edge):
  """
  Given pair of vertices (edge variable) add an edge to existing graph.
  We consider simple, undirected graphs, as symmetric digraphs without loops.
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Loops are not allowed!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)


## Reading and writing graphs to a file

In [8]:
def graph_from_edges(filename, directed = 0):
  """
  Read the graph from file, that in each line contains either the description
  of one edge (two words) or the description of a vertex (one word).
  The result is a graph in a form of neighbourhood list.
  filename contains the whole path to the file.
  """
  graph = {}
  file = open(filename, "r")    # open the file to read
  for line in file:             # for each line of the file
    words = line.strip().split()  # splits the line into words
    if len(words) == 1:         # one word - the vertex description
      add_vertex(graph, words[0])
    elif len(words) >= 2:       # more words, I use first two as an edge description
      if directed:
        add_arc(graph, (words[0], words[1]))
      else:
        add_edge(graph, (words[0], words[1]))
  file.close()
  return graph


def graph_to_neighbourlist(graph, filename):
  """
  Writing of a graph (given as a dictionary/neighbouring list)
  to a textfile file (as a neghbour list)
  """
  file = open(filename, "w")
  for v in graph:
    neigh_list = f"{v}:"
    for u in graph[v]:
      neigh_list = neigh_list + f" {u}"
    neigh_list = neigh_list + "\n"
    file.write(neigh_list)
  file.close()

## Use of code

In [5]:
%%writefile edges.txt
a b
b c
b d
d
d c
e
f


Writing edges.txt


In [6]:
%cat edges.txt

a b
b c
b d
d
d c
e
f


In [7]:
graph1 = graph_from_edges("edges.txt")
print_graph(graph1)

a :  b
b :  a  c  d
c :  b  d
d :  b  c
e :
f :


In [9]:
graph_to_neighbourlist(graph1, "neigh.txt")

In [10]:
%cat "neigh.txt"

a: b
b: a c d
c: b d
d: b c
e:
f:


In [ ]:
vertices = ["a", "b", "c", "d"]
matrix = np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,0,1]])
print(vertices)
print(matrix)
print("---------------------------")
print_matrix(vertices, matrix)
print("---------------------------")
print_matrix(None,matrix)

['a', 'b', 'c', 'd']
[[0 1 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 0 1]]
---------------------------
a :  b
b :  a  c
c :  b  d
d :  d
---------------------------
1 :  2
2 :  1  3
3 :  2  4
4 :  4


In [ ]:
graph = {
  "a": ["b"],
  "b": ["a", "c"],
  "c": ["b", "d"],
  "d": ["c"]
}
print(graph)
print("---------------------------")
print_graph(graph)

{'a': ['b'], 'b': ['a', 'c'], 'c': ['b', 'd'], 'd': ['c']}
---------------------------
a :  b
b :  a  c
c :  b  d
d :  c


In [ ]:
add_vertex(graph, "e")
print_graph(graph)

a :  b
b :  a  c
c :  b  d
d :  c
e :


In [ ]:
add_edge(graph, ["e", "f"])
print_graph(graph)

a :  b
b :  a  c
c :  b  d
d :  c
e :  f
f :  e


In [ ]:
add_arc(graph, ["e", "a"]) # breaking the symmetry
print_graph(graph)

a :  b
b :  a  c
c :  b  d
d :  c
e :  f  a
f :  e


In [ ]:
add_edge(graph, ["a", "e"]) # restoring the symmetry
print_graph(graph)

a :  b  e
b :  a  c
c :  b  d
d :  c
e :  f  a
f :  e


In [ ]:
add_edge(graph, ["e", "f"]) # do nothing, an edge already exists
print_graph(graph)

a :  b  e
b :  a  c
c :  b  d
d :  c
e :  f  a
f :  e


In [ ]:
add_edge(graph, ["e", "e"]) # an error

ValueError: Loops are not allowed!

In [ ]:
add_arc(graph, ["e", "e"]) # OK - loops are allowed in digraphs
print_graph(graph)

a :  b  e
b :  a  c
c :  b  d
d :  c
e :  f  a  e
f :  e


## Random graphs generator in the $G(n,p)$ model.

In [ ]:
# for repeatness
seed(2024)

In [ ]:
#draw a graph G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if random() < p:
      add_edge(random_graph, [i, j])

print_graph(random_graph)

1 :  5  10
2 :  3  5  9  10
3 :  2  8
4 :  6  7  8  10
5 :  1  2  10
6 :  4  8  10
7 :  4  9  10
8 :  3  4  6
9 :  2  7
10 :  1  2  4  5  6  7
