Package import.

In [ ]:
import numpy as np
from random import random, seed

## Graph functions

In [ ]:
#Esta función se encarga de imprimir un grafo representado por una matriz de adyacencia. Aquí hay un desglose de su funcionamiento
def print_matrix(vertices, matrix):
  #le damos los vertices(Una lista que representa los nombres o identificadores de los vértices del grafo) y matrix (Una matriz que representa las conexiones entre los vértices. Si matrix[i][j] es True, significa que hay una conexión (arista) entre el vértice i y el vértice j)
  """
  Printing a graph given by adjacency matrix
  """
  n = len(matrix) #con esto obtengo el num de vertices = tamaño matriz (aqui hacemos la comprobacion len(vertices) == n)
  if (vertices is not None) and (len(vertices) == n):
    vv = vertices
  else:
    vv = range(1, n+1)
  for i in range(n):
    #lo de end="" es para que no salte de linea
    print(vv[i], ":", end="")
    for j in range(n):
      #verificamos si hay conexiones (aristas) a otros vertices
      if matrix[i, j]:
        print(" ", vv[j], end="")
    print("")

#el va a usar la primera
def print_graph(graph):
  """
  Printing of a graph (given as a dictionary/neighbouring list)
  """
  for v in graph:
    print(v, ":", end="") #ponemos lo del end para que no salte de linea
    for u in graph[v]:
      print(" ", u, end="")
    print("")

## Making and modyfing graphs

In [ ]:
def add_vertex(graph, vertex):
  """
  Add a new vertex to an existing graph
  """
  if vertex not in graph:
    #Si el vértice no está, se añade al diccionario con graph[vertex] = [], inicializando su lista de conexiones (adyacencias) como vacía.
    graph[vertex] = []

def add_arc(graph, arc):
  #arc: Una tupla que contiene dos vértices, (u, v), donde u es el vértice de origen y v es el vértice de destino
  #agrega un arco (una conexión direccional) entre dos vértices en un grafo dirigido
  """
  Given pair of vertices (arc variable) add an arc to an existing graph
  We consider simple, directed graphs.
  """
  u, v = arc #descomponemos la tupla arc en los vertices u y v
  add_vertex(graph, u)  #nos aseguramos de que ambos vertices existen en el grafo
  add_vertex(graph, v)
  if v not in graph[u]: #Verifica si v no está ya en la lista de adyacencias de u
    graph[u].append(v)

def add_edge(graph, edge):
  # agrega una arista (una conexión bidireccional) entre dos vértices en un grafo no dirigido.
  # edge: Una tupla que contiene dos vértices, (u, v).
  """
  Given pair of vertices (edge variable) add an edge to existing graph.
  We consider simple, undirected graphs, as symmetric digraphs without loops.
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("A loop created!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)


## Use of code

In [ ]:
vertices = ["a", "b", "c", "d"]
matrix = np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,0,1]])
print(vertices)
print(matrix)
print("---------------------------")
print_matrix(vertices, matrix)
print("---------------------------")
print_matrix(None,matrix)

['a', 'b', 'c', 'd']
[[0 1 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 0 1]]
---------------------------
a :  b
b :  a  c
c :  b  d
d :  d
---------------------------
1 :  2
2 :  1  3
3 :  2  4
4 :  4


In [ ]:
graph = {
  "a": ["b"],
  "b": ["a", "c"],
  "c": ["b", "d"],
  "d": ["c"]
}
print(graph)
print("---------------------------")
print_graph(graph)

{'a': ['b'], 'b': ['a', 'c'], 'c': ['b', 'd'], 'd': ['c']}
---------------------------
a :  b
b :  a  c
c :  b  d
d :  c


In [ ]:
add_vertex(graph, "e")
print_graph(graph)

a :  b
b :  a  c
c :  b  d
d :  c
e :


In [ ]:
add_edge(graph, ["e", "f"])
print_graph(graph)

a :  b
b :  a  c
c :  b  d
d :  c
e :  f
f :  e


In [ ]:
add_arc(graph, ["e", "a"]) # breaking the symmetry
print_graph(graph)

a :  b
b :  a  c
c :  b  d
d :  c
e :  f  a
f :  e


In [ ]:
add_arc(graph, ["a", "e"]) # restoring the symmetry
print_graph(graph)

a :  b  e
b :  a  c
c :  b  d
d :  c
e :  f  a
f :  e


In [ ]:
add_edge(graph, ["e", "f"]) # do nothing, an edge already exists
print_graph(graph)

a :  b  e
b :  a  c
c :  b  d
d :  c
e :  f  a
f :  e


In [ ]:
add_edge(graph, ["e", "e"]) # an error

ValueError: A loop created!

In [ ]:
add_arc(graph, ["e", "e"]) # OK - loops are allowed in digraphs
print_graph(graph)

a :  b  e
b :  a  c
c :  b  d
d :  c
e :  f  a  e
f :  e


## Random graphs generator in a $G(n,p)$ model.

In [ ]:
# for repeatness
seed(2024)

In [ ]:
#draw a graph G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if random() < p:
      add_edge(random_graph, [i, j])

print_graph(random_graph)

1 :  5  10
2 :  3  5  9  10
3 :  2  8
4 :  6  7  8  10
5 :  1  2  10
6 :  4  8  10
7 :  4  9  10
8 :  3  4  6
9 :  2  7
10 :  1  2  4  5  6  7


## Lat task 1 (creating and modifying graphs)

In [ ]:
#Write a function random_graph(n, p), which returns a random graph in G(n, p) model — n vertices, an existence of each edge is independent and holds with probability p.
#Escribe una función random_graph(n, p), que devuelve un grafo aleatorio en el modelo 𝐺(𝑛,𝑝): n vértices, donde la existencia de cada arista es independiente y se mantiene con probabilidad 𝑝
def random_graph(n, p):
    graph = {}
    for i in range(n):
      ##Se añade al diccionario con graph[i] = [], inicializando su lista de conexiones (adyacencias) como vacía.
        graph[i] = []

    for u in range(n):
        for v in range(u + 1, n):  # Evitamos el contar doblemente con lo de +1
            if random() < p:
                graph[u].append(v)
                graph[v].append(u)

    return graph

In [ ]:
#Write a function graph_to_matrix(graph), which converts a graph given by neighbour list into matrix representation and returns a matrix and a sequence of vertices.
#Escribe una función graph_to_matrix(graph), que convierte un grafo dado en forma de lista de adyacencia en una representación de matriz y devuelve una matriz y una secuencia de vértices.

'''
#Function with pure adjacency list
def graph_to_matrix(graph):
    n = len(graph)
    matrix = np.zeros((n, n), dtype=int)

    for i in range(n):
        for neighbor in graph[i]:
            matrix[i][neighbor] = 1  # Ponemos un 1 para marcar

    return matrix, list(range(n))

#list(range(n)) genera una lista de números enteros que van desde 0 hasta n-1
'''

#Function with neighbour list (python dictionary)
def graph_to_matrix(graph):
    vertices = list(graph.keys())
    n = len(vertices)
    matrix = np.zeros((n, n), dtype=int)

    for i in range(n):
        for neighbor in graph[vertices[i]]:
            matrix[i][neighbor] = 1  #Ponemos un 1 para marcar

    return matrix, vertices

In [ ]:
#Write a function matrix_to_graph(vertices, matrix) which converts in the opposite direction — convertiing a matrix (and a sequence of vertex labels) into a form of neighbour list (python dictionary).
#Escribe una función matrix_to_graph(vertices, matrix), que convierte en la dirección opuesta: convirtiendo una matriz (y una secuencia de etiquetas de vértices) en una forma de lista de adyacencia (diccionario en Python).

def matrix_to_graph(vertices, matrix):
    graph = {vertex: [] for vertex in vertices}

    n = len(vertices)
    for i in range(n):
        for j in range(n):
          #buscamos una arista
            if matrix[i][j] == 1:
                graph[vertices[i]].append(vertices[j])

    return graph

In [ ]:
#Write a function cycle(n), which return a cycle on n vertices.
#Escribe una función cycle(n), que devuelve un ciclo en n vértices
def cycle(n):
    if n < 3:
        raise ValueError("To be a cycle we need at least 3 vertices")

    graph = {i: [] for i in range(n)}

    for i in range(n):
        #concectamos el vertice i con el i+1
        graph[i].append((i + 1) % n)
        #concectamos el vertice previo, es decir, el i+1 con i (unidireccional)
        graph[(i + 1) % n].append(i)
        #hago lo de (i+1) %n pq asi cuando lleguemos al ultimo vertice n-1 se conecte al vertice 0 que es el del principio, ya que si i=n-1, i+1 seria n pero estamos trabajando con vertices. Po eso usamos el %n para que sea n%n y ir al 0

    return graph

In [ ]:
##TEST TO PROVE THE FUNCTIONS
def test_functions():
    # Probamos random_graph con n = 5 y p = 0.5
    print("---- Random Graph Test ----")
    seed(42)  # Fijamos la semilla para tener resultados reproducibles
    g = random_graph(5, 0.5)
    print("Grafo aleatorio (n=5, p=0.5):", g)

    # Probamos graph_to_matrix y matrix_to_graph
    print("\n---- Graph to Matrix and Matrix to Graph Test ----")
    g_matrix, vertices = graph_to_matrix(g)
    print("Matriz de adyacencia:\n", g_matrix)
    g_back = matrix_to_graph(vertices, g_matrix)
    print("Grafo reconstruido desde la matriz:", g_back)

    # Probamos el ciclo con n = 5
    print("\n---- Cycle Test ----")
    c = cycle(5)
    print("Ciclo de 5 vértices:", c)
    c_matrix, vertices = graph_to_matrix(c)
    print("Matriz del ciclo:\n", c_matrix)
    c_back = matrix_to_graph(vertices, c_matrix)
    print("Ciclo reconstruido desde la matriz:", c_back)

# Ejecutamos las pruebas
test_functions()

---- Random Graph Test ----
Grafo aleatorio (n=5, p=0.5): {0: [2, 3, 4], 1: [], 2: [0, 3, 4], 3: [0, 2, 4], 4: [0, 2, 3]}

---- Graph to Matrix and Matrix to Graph Test ----
Matriz de adyacencia:
 [[0 0 1 1 1]
 [0 0 0 0 0]
 [1 0 0 1 1]
 [1 0 1 0 1]
 [1 0 1 1 0]]
Grafo reconstruido desde la matriz: {0: [2, 3, 4], 1: [], 2: [0, 3, 4], 3: [0, 2, 4], 4: [0, 2, 3]}

---- Cycle Test ----
Ciclo de 5 vértices: {0: [1, 4], 1: [0, 2], 2: [1, 3], 3: [2, 4], 4: [3, 0]}
Matriz del ciclo:
 [[0 1 0 0 1]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [1 0 0 1 0]]
Ciclo reconstruido desde la matriz: {0: [1, 4], 1: [0, 2], 2: [1, 3], 3: [2, 4], 4: [0, 3]}
