<a href="https://colab.research.google.com/github/pgordin/GraphsSN2024_1/blob/main/Task1_graphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from random import random, seed

###Functions from classes


In [ ]:
def print_matrix(vertices, matrix):
  """
  Printing a graph given by adjacency matrix
  """
  n = len(matrix)
  if (vertices is not None) and (len(vertices) == n):
    vv = vertices
  else:
    vv = range(1, n+1)
  for i in range(n):
    print(vv[i], ":", end="")
    for j in range(n):
      if matrix[i, j]:
        print(" ", vv[j], end="")
    print("")

def print_graph(graph):
  """
  Printing of a graph (given as a dictionary/neighbouring list)
  """
  for v in graph:
    print(v, ":", end="")
    for u in graph[v]:
      print(" ", u, end="")
    print("")

def add_vertex(graph, vertex):
  """
  Add a new vertex to an existing graph
  """
  if vertex not in graph:
    graph[vertex] = []

def add_arc(graph, arc):
  """
  Given pair of vertices (arc variable) add an arc to an existing graph
  We consider simple, directed graphs.
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)

def add_edge(graph, edge):
  """
  Given pair of vertices (edge variable) add an edge to existing graph.
  We consider simple, undirected graphs, as symmetric digraphs without loops.
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("A loop created!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)

#Task

In [ ]:
seed(2024)

In [ ]:
def random_graph(n, p):
    random_graph = {}
    for i in range(0, n):
        add_vertex(random_graph, i)
        for j in range(0, i):
            if random() < p:
                add_edge(random_graph, [i, j])
    return random_graph

graph = random_graph(10, 1/3)
print_graph(graph)

0 :  4  9
1 :  2  4  8  9
2 :  1  7
3 :  5  6  7  9
4 :  0  1  9
5 :  3  7  9
6 :  3  8  9
7 :  2  3  5
8 :  1  6
9 :  0  1  3  4  5  6


In [ ]:
def adjacency_matrix_to_dict(adj_matrix):
    """
    Converts an adjacency matrix to a dictionary representation of a graph.
    """
    graph_dict = {}

    for i, row in enumerate(adj_matrix):
        graph_dict[i] = [j for j, val in enumerate(row) if val == 1]

    return graph_dict

In [ ]:
def dict_to_adjacency_matrix(graph_dict):
    """
    Converts a dictionary representation of a graph to an adjacency matrix.
    Works for matrices numered from 0 to n-1.
    """
    n = len(graph_dict)

    adj_matrix = np.zeros((n, n), dtype=int)

    # Populate the adjacency matrix
    for node, neighbors in graph_dict.items():
        for neighbor in neighbors:
            adj_matrix[node][neighbor] = 1

    return adj_matrix

In [ ]:
graph_adj = dict_to_adjacency_matrix(graph)
print(graph_adj)
graph_dict = adjacency_matrix_to_dict(graph_adj)
print(graph_dict)

[[0 0 0 0 1 0 0 0 0 1]
 [0 0 1 0 1 0 0 0 1 1]
 [0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1 1 0 1]
 [1 1 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 1 0 1]
 [0 0 0 1 0 0 0 0 1 1]
 [0 0 1 1 0 1 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0]
 [1 1 0 1 1 1 1 0 0 0]]
{0: [4, 9], 1: [2, 4, 8, 9], 2: [1, 7], 3: [5, 6, 7, 9], 4: [0, 1, 9], 5: [3, 7, 9], 6: [3, 8, 9], 7: [2, 3, 5], 8: [1, 6], 9: [0, 1, 3, 4, 5, 6]}


In [ ]:
def cycle(n):
    """
    Creates an adjacency matrix for a cycle graph with n vertices.
    """

    adj_matrix = np.zeros((n, n), dtype=int)

    for i in range(n):
        if i > 0:
            adj_matrix[i][i - 1] = 1
            adj_matrix[i - 1][i] = 1

    adj_matrix[0][n - 1] = 1
    adj_matrix[n - 1][0] = 1

    return adj_matrix

cycle_graph = cycle(4)
print(cycle_graph)


[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
